base_url = "https://blog.eromanga.top"
compile_sass = false
build_search_index = false
default_language = "zh"
description = "liyang`s blog"
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
